id: OB_GSEA
description: Comparison of Single Sample Gene Set Enrichment Analysis methods for functional analysis in research and diagnostics
version: "1.0"
benchmarker: Luca Robinson, luca.robinson@regionh.dk
benchmark_yaml_spec: 0.5.0

software_backend: apptainer
software_environments:
  R_base:
    description: "R 4.5.1 base"
    apptainer: oras://quay.io/luca_robinson/ob_gsea/r_base:latest
  R_singscore:
    description: "R 4.5.1 with singscore dependencies"
    apptainer: oras://quay.io/luca_robinson/ob_gsea/r_singscore:latest
  R_gsva:
    description: "R 4.5.1 with GSVA dependencies"
    apptainer: oras://quay.io/luca_robinson/ob_gsea/r_gsva:latest
  R_fgsea:
    description: "R 4.5.1 with fGSEA dependencies"
    apptainer: oras://quay.io/luca_robinson/ob_gsea/r_fgsea:latest
  R_ucell:
    description: "R 4.5.1 with UCell dependencies"
    apptainer: oras://quay.io/luca_robinson/ob_gsea/r_ucell:latest
  Py_metrics:
    description: "Python container for metrics"
    apptainer: oras://quay.io/luca_robinson/ob_gsea/py_metrics:latest


metric_collectors:
- id: Metricsplotting
  name: Metrics plotting per dataset
  software_environment: Py_metrics
  repository:
    url: https://github.com/cphgeno/OB_GSEA-MetricsCollector.git
    commit: main
  inputs:
  - MetricsValidation.flag
  outputs:
  - id: Metricsplotting.complete
    path: '{name}/plotting_wrapper_complete.flag'

stages:
#################
#Data collection#
#################
- id: data
  modules:
  - id: TCGAnormal
    name: TCGA counts and sex manual analysis
    software_environment: R_base
    repository:
      url: https://github.com/cphgeno/OB_GSEA-data_collection.git
      commit: main
    parameters:
    - genesets:
      - Tissues_DESeq
      - Sex_Manual
      wreference:
      - Universal
      - VSdf

  - id: TCGAtumour
    name: TCGA counts and sex manual analysis
    software_environment: R_base
    repository:
      url: https://github.com/cphgeno/OB_GSEA-data_collection.git
      commit: main
    parameters:
    - genesets:
      - CancerType_DLA
      - Sex_Manual
      wreference:
      - Universal
      - VSdf

  - id: TCGABRCA
    name: TCGA counts for Breast cancer with subtype
    software_environment: R_base
    repository:
      url: https://github.com/cphgeno/OB_GSEA-data_collection.git
      commit: main
    parameters:
    - genesets:
      - BreastCancer_MSigDBSmid
      wreference:
      - Universal
      - VSdf

  - id: GTEX
    name: GTEX counts testing data
    software_environment: R_base
    repository:
      url: https://github.com/cphgeno/OB_GSEA-data_collection.git
      commit: main
    parameters:
    - genesets:
      - Tissues_DESeq
      - Sex_Manual
      wreference:
      - Universal

  - id: GSE214654
    name: GSE214654 BRAIN counts
    software_environment: R_base
    repository:
      url: https://github.com/cphgeno/OB_GSEA-data_collection.git
      commit: main
    parameters:
    - genesets:
      - Neuro_MSigDBGOBP
      wreference:
      - Universal
      - VSdf

  - id: CellCycleDB
    name: CellCycleDB Cell cycle analysis
    software_environment: R_base
    repository:
      url: https://github.com/cphgeno/OB_GSEA-data_collection.git
      commit: main
    parameters:
    - genesets:
      - CellCycle_MSigDBReactome
      - CellCycle_MSigDBWhitfield
      wreference:
      - Universal
      - VSdf

  - id: O2DB
    name: O2DB Hypoxia and Hyperoxia counts
    software_environment: R_base
    repository:
      url: https://github.com/cphgeno/OB_GSEA-data_collection.git
      commit: main
    parameters:
    - genesets:
      - Oxia_MSigDB
      - Oxia_MSigDBHallmark
      wreference:
      - Universal
      - VSdf

  outputs:
  - id: data.counts
    path: '{dataset}-counts.tsv'
  - id: data.metadata
    path: '{dataset}-metadata.tsv'
  - id: data.genesets
    path: '{dataset}-GenesetsOI.gmt'
  - id: data.referencecounts
    path: '{dataset}-REFERENCE-counts.tsv'

###############
#Preprocessing#
###############
- id: preprocessing
  modules:
  - id: ranking
    name: Data preparation for input to GSEA tools
    software_environment: R_base
    repository:
      url: https://github.com/cphgeno/OB_GSEA-preprocessing.git
      commit: main
  inputs:
  - data.counts
  - data.metadata
  - data.genesets
  - data.referencecounts
  outputs:
  - id: preprocessing.sampleranks
    path: '{dataset}-sampleranks.tsv'
  - id: preprocessing.samplediffranks
    path: '{dataset}-samplediffranks.tsv'
  - id: preprocessing.referenceranks
    path: '{dataset}-referenceranks.tsv'
  - id: preprocessing.meta
    path: '{dataset}-metadata_preprocessed.tsv'
  - id: preprocessing.genesets
    path: '{dataset}-GenesetsOI_preprocessed.gmt'

###############
#Tools section#
###############
- id: ScoringTools
  modules:
  - id: fGSEA
    software_environment: R_fgsea
    repository:
      url: https://github.com/cphgeno/OB_GSEA-fGSEA_scoring.git
      commit: main
    parameters:
    - input_type:
      - RankExpr
      - DeltaCentroid
  
  - id: GSVA
    software_environment: R_gsva
    repository:
      url: https://github.com/cphgeno/OB_GSEA-GSVA_scoring.git
      commit: main
    parameters:
    - algorithm:
      - gsva
      - plage
      - zscore
      input_type:
      - RankExpr
      - DeltaCentroid
      - RankReference
  
  - id: singscore
    software_environment: R_singscore
    repository:
      url: https://github.com/cphgeno/OB_GSEA-singscore_scoring.git
      commit: main
    parameters:
    - input_type:
      - RankExpr
      - DeltaCentroid
  
  - id: ssGSEA
    software_environment: R_gsva
    repository:
      url: https://github.com/cphgeno/OB_GSEA-ssGSEA_scoring.git
      commit: main
    parameters:
    - input_type:
      - RankExpr
      - DeltaCentroid
  
  - id: UCell
    software_environment: R_ucell
    repository:
      url: https://github.com/cphgeno/OB_GSEA-UCell_scoring.git
      commit: main
    parameters:
    - input_type:
      - RankExpr
      - DeltaCentroid
  
  inputs:
  - preprocessing.sampleranks
  - preprocessing.samplediffranks
  - preprocessing.referenceranks
  - preprocessing.meta
  - preprocessing.genesets
  outputs:
  - id: ScoringTools.fullNES
    path: '{dataset}-fullNES.tsv'

#################
#Metrics section#
#################
- id: MetricsValidation
  modules:
  - id: top1validation
    name: Top1 metrics computation for validation datasets
    software_environment: Py_metrics
    repository:
      url: https://github.com/cphgeno/OB_GSEA-top1validation.git
      commit: master
  - id: AUCvalidation
    name: AUC metrics computation for validation datasets
    software_environment: Py_metrics
    repository:
      url: https://github.com/cphgeno/OB_GSEA-AUCvalidation.git
      commit: master
  inputs:
  - preprocessing.meta
  - ScoringTools.fullNES
  outputs:
  - id: MetricsValidation.flag
    path: '{dataset}-metrics_complete.flag'
